# Generated by Django 4.2.13 on 2024-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=180, null=True, unique=True),
        ),
    ]
